### ISSUE TITLE
Add attendance tracking support

### ISSUE THREAD

**Issue by Lemmings19** [thatsmybis/thatsmybis#45]
Add features for tracking raid attendance and displaying that attendance throughout the website.

- Decide if attendance will be broken down by pulls, bosses killed, or raid count attended (with the option of the officers to assign a float of their choosing; 1.0 being full attendance for that raid).
- Draw mockups for the attendance input page.
- Draw mockups for the attendance display page (single raid and raid list).

- [x] Rename/refactor `raids` to `raid_groups`.

---

- [x] Make page+functionality for creating attendance/raid.
- [x] Make page+functionality for editing attendance/raid.
- [x] Make page+functionality for copying attendance/raid.
- [x] Make page for viewing attendance/raid.

---

- [x] Feature for guilds to toggle attendance feature on/off.

---

- Show attendance stats beside characters.
- `sum(attendance)` as well as `sum(attendance)/sum(was_expected)`?
- [x] Show on character page.
- [x] Show on member page by characters.
- [x] Show member average attendance on member page?
- [x] Show member average attendance on member list page?
- [x] Show on roster page beside characters.
- [x] Show on loot page beside characters.
- [x] Show on prio assignment page beside wishlisted items.

---

- [x] Show detailed attendance breakdown on character page.
- [x] Show detailed attendance breakdown on member page?

---

- [x] ~~Show an overall attendance breakdown table, filterable by raid and class.~~ Member and Roster pages do this.

---

- [x] Create a `raid` table & model.
- [x] `raid_characters` table should have columns similar to `attendance (float 0.0-1.0)` (pulls present for divided by pulls the raid made?), `was_expected`, `is_trial`(not sure if we need this one), `raid_group_id` (to indicate if they belonged to a different group at the time?), `character_id`.

---

- [ ] Take into consideration how imports will work and what the import format might look like.
- [ ] Add permission for editing raid groups (different from editing raids)

---

For a later release?

- [ ] Make sure new API endpoints are secure.
- [ ] Create a feature for linking `batches`, `raid groups`, `instances`, `characters`, and `items` to `raids`.
- [ ] Create a page for listing batches. (show `batch name`, `# items assigned`, `raid group name`, `date submitted`)

Branches:
- Merge/deploy first: https://github.com/thatsmybis/thatsmybis/pull/131
- Merge/deploy second: https://github.com/thatsmybis/thatsmybis/pull/132
- [ ] Update production `.env` with cache variables.
